#  ----------------------------------------------------#
#  MyServer - Configuration file                       #
#  ----------------------------------------------------#
#  Author: Sicka_gp                                    #
#  ----------------------------------------------------#
Plugin:
   Config_version: 1
   Plugin_version: 0
   AutoUpdate: true