#  ----------------------------------------------------#
#  MyServer - Configuration file                       #
#  ----------------------------------------------------#
#  Author: Sicka_gp                                    #
#  ----------------------------------------------------#
Config_version: 1

Plugin:
   Plugin_version: 0
   AutoUpdate: true